//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gpw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friends_mobile
    {
        public long id { get; set; }
        public string number_1 { get; set; }
        public string number_2 { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
