//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gpw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friend
    {
        public long id { get; set; }
        public string user1 { get; set; }
        public string user2 { get; set; }
        public Nullable<int> quan_he_id { get; set; }
        public Nullable<int> do_sau { get; set; }
    }
}
