//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gpw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gia_pha
    {
        public long id { get; set; }
        public Nullable<long> thanh_vien_id { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public Nullable<long> tv_id_1 { get; set; }
        public Nullable<long> tv_id_2 { get; set; }
        public Nullable<int> q_h_id { get; set; }
    }
}
