//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gpw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quan_he_thanh_vien
    {
        public long id { get; set; }
        public string ten_thanh_vien { get; set; }
        public Nullable<int> quan_he_id { get; set; }
        public string ten_quan_he { get; set; }
        public Nullable<long> thanh_vien_id { get; set; }
        public string que_quan { get; set; }
        public Nullable<double> qq_lon { get; set; }
        public Nullable<double> qq_lat { get; set; }
        public Nullable<long> thanh_vien_qh_id { get; set; }
    }
}
