//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gpw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thanh_vien
    {
        public long id { get; set; }
        public string ho_ten { get; set; }
        public string dia_chi { get; set; }
        public string so_cmt { get; set; }
        public string nghe_nghiep { get; set; }
        public string hoc_van { get; set; }
        public string hinh_anh { get; set; }
        public string biet_danh { get; set; }
        public Nullable<int> doi_thu { get; set; }
        public string gioi_tinh { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<int> trang_thai { get; set; }
        public Nullable<int> quyen_han { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
        public string cq_ctac { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string trinh_do { get; set; }
        public string so_dien_thoai { get; set; }
    }
}
