//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gpw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_business
    {
        public long id { get; set; }
        public Nullable<long> user_id { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public string image { get; set; }
        public string website { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
    }
}
